import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Check, FileText, Key, ChevronDown, ChevronUp, Brain, Download } from 'lucide-react';
import clsx from 'clsx';
import {
    Document, Packer, Paragraph, TextRun, HeadingLevel,
    AlignmentType, BorderStyle, ShadingType, Table, TableRow,
    TableCell, WidthType, Header, Footer, PageNumber,
    NumberFormat, convertInchesToTwip, UnderlineType,
} from 'docx';
import { saveAs } from 'file-saver';

// ─── Bloom's badge styles (website only) ─────────────────────────────────────
const BLOOMS_BADGE_STYLES = {
    remember:   { label: 'Remember',   classes: 'bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300 border-blue-200 dark:border-blue-800' },
    understand: { label: 'Understand', classes: 'bg-cyan-100 text-cyan-700 dark:bg-cyan-900/40 dark:text-cyan-300 border-cyan-200 dark:border-cyan-800' },
    apply:      { label: 'Apply',      classes: 'bg-green-100 text-green-700 dark:bg-green-900/40 dark:text-green-300 border-green-200 dark:border-green-800' },
    analyze:    { label: 'Analyze',    classes: 'bg-purple-100 text-purple-700 dark:bg-purple-900/40 dark:text-purple-300 border-purple-200 dark:border-purple-800' },
    evaluate:   { label: 'Evaluate',   classes: 'bg-orange-100 text-orange-700 dark:bg-orange-900/40 dark:text-orange-300 border-orange-200 dark:border-orange-800' },
    create:     { label: 'Create',     classes: 'bg-pink-100 text-pink-700 dark:bg-pink-900/40 dark:text-pink-300 border-pink-200 dark:border-pink-800' },
};

// ─── Shared colour constants (in hex without #, for docx) ────────────────────
const INDIGO   = '4F46E5';
const INDIGO_L = 'EEF2FF'; // light indigo background
const EMERALD  = '059669';
const EMERALD_L = 'D1FAE5';
const BLUE_L   = 'EFF6FF';
const BLUE_T   = '1D4ED8';
const GRAY_D   = '1E293B';
const GRAY_M   = '475569';
const GRAY_L   = 'F1F5F9';
const WHITE    = 'FFFFFF';

// ─── Helper: make a shaded paragraph (coloured background row) ───────────────
function shadedPara(children, fillColor, spacing = { before: 80, after: 80 }) {
    return new Paragraph({
        children,
        shading: { type: ShadingType.SOLID, color: fillColor, fill: fillColor },
        spacing,
        indent: { left: convertInchesToTwip(0.1) },
    });
}

// ─── Helper: plain paragraph ─────────────────────────────────────────────────
function para(children, opts = {}) {
    return new Paragraph({ children, ...opts });
}

// ─── Helper: horizontal rule ─────────────────────────────────────────────────
function hrPara() {
    return new Paragraph({
        children: [],
        border: {
            bottom: { color: 'C7D2FE', space: 1, style: BorderStyle.SINGLE, size: 6 },
        },
        spacing: { before: 60, after: 60 },
    });
}

// ─── Build Question Paper .docx ───────────────────────────────────────────────
async function downloadQuestionDocx(mcqs) {
    const OPT_LETTERS = ['A', 'B', 'C', 'D', 'E', 'F'];

    const children = [
        // ── Title block ──────────────────────────────────────────────────
        shadedPara(
            [new TextRun({ text: 'EduMate', bold: true, size: 32, color: WHITE, font: 'Calibri' })],
            INDIGO,
            { before: 0, after: 0 },
        ),
        shadedPara(
            [new TextRun({ text: `Question Paper   |   Total Questions: ${mcqs.length}   |   Generated by EduMate AI`, size: 18, color: 'C7D2FE', font: 'Calibri' })],
            '3730A3',
            { before: 40, after: 40 },
        ),
        para([], { spacing: { before: 200, after: 0 } }),
    ];

    mcqs.forEach((mcq, idx) => {
        const qNo = mcq.question_no || String(idx + 1);

        // Question number header (shaded strip — NO bloom level)
        children.push(
            shadedPara(
                [new TextRun({ text: `Q${qNo}`, bold: true, size: 22, color: INDIGO, font: 'Calibri' })],
                INDIGO_L,
                { before: 120, after: 60 },
            )
        );

        // Question text
        children.push(
            para(
                [new TextRun({ text: mcq.question, size: 22, color: GRAY_D, font: 'Calibri' })],
                { spacing: { before: 80, after: 100 }, indent: { left: convertInchesToTwip(0.1) } }
            )
        );

        // Options
        (mcq.answer_options || []).forEach((opt, oi) => {
            children.push(
                para(
                    [
                        new TextRun({ text: `${OPT_LETTERS[oi] ?? oi + 1})  `, bold: true, size: 20, color: GRAY_M, font: 'Calibri' }),
                        new TextRun({ text: opt, size: 20, color: GRAY_M, font: 'Calibri' }),
                    ],
                    { spacing: { before: 40, after: 40 }, indent: { left: convertInchesToTwip(0.3) } }
                )
            );
        });

        // Separator (except last)
        if (idx < mcqs.length - 1) {
            children.push(hrPara());
        }
    });

    const doc = new Document({
        sections: [{
            properties: {},
            headers: {
                default: new Header({
                    children: [
                        para([
                            new TextRun({ text: 'EduMate AI Assessment  —  Question Paper', size: 16, color: '94A3B8', font: 'Calibri' }),
                        ], { alignment: AlignmentType.RIGHT }),
                    ],
                }),
            },
            footers: {
                default: new Footer({
                    children: [
                        para([
                            new TextRun({ text: 'Page ', size: 16, color: '94A3B8', font: 'Calibri' }),
                            new TextRun({ children: [PageNumber.CURRENT], size: 16, color: '94A3B8', font: 'Calibri' }),
                            new TextRun({ text: ' of ', size: 16, color: '94A3B8', font: 'Calibri' }),
                            new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 16, color: '94A3B8', font: 'Calibri' }),
                        ], { alignment: AlignmentType.CENTER }),
                    ],
                }),
            },
            children,
        }],
    });

    const blob = await Packer.toBlob(doc);
    saveAs(blob, 'EduMate_Question_Paper.docx');
}

// ─── Build Answer Key .docx ───────────────────────────────────────────────────
async function downloadAnswerKeyDocx(mcqs) {
    const OPT_LETTERS = ['A', 'B', 'C', 'D', 'E', 'F'];

    const children = [
        // ── Title block ──────────────────────────────────────────────────
        shadedPara(
            [new TextRun({ text: 'EduMate', bold: true, size: 32, color: WHITE, font: 'Calibri' })],
            EMERALD,
            { before: 0, after: 0 },
        ),
        shadedPara(
            [new TextRun({ text: `Answer Key   |   Total Questions: ${mcqs.length}   |   For Professor Use Only`, size: 18, color: 'A7F3D0', font: 'Calibri' })],
            '047857',
            { before: 40, after: 40 },
        ),
        para([], { spacing: { before: 200, after: 0 } }),
    ];

    mcqs.forEach((mcq, idx) => {
        const qNo = mcq.question_no || String(idx + 1);

        // Question number header (shaded strip — NO bloom level)
        children.push(
            shadedPara(
                [new TextRun({ text: `Q${qNo}`, bold: true, size: 22, color: EMERALD, font: 'Calibri' })],
                EMERALD_L,
                { before: 120, after: 60 },
            )
        );

        // Question text
        children.push(
            para(
                [new TextRun({ text: mcq.question, size: 22, color: GRAY_D, font: 'Calibri' })],
                { spacing: { before: 80, after: 100 }, indent: { left: convertInchesToTwip(0.1) } }
            )
        );

        // Options — highlight correct one
        (mcq.answer_options || []).forEach((opt, oi) => {
            const isCorrect =
                opt === mcq.correct_answer ||
                opt.startsWith(`${mcq.correct_answer})`) ||
                opt.startsWith(`${mcq.correct_answer}.`);

            const label = `${OPT_LETTERS[oi] ?? oi + 1})`;

            if (isCorrect) {
                children.push(
                    shadedPara(
                        [
                            new TextRun({ text: `✓  ${label}  `, bold: true, size: 20, color: EMERALD, font: 'Calibri' }),
                            new TextRun({ text: opt, bold: true, size: 20, color: EMERALD, font: 'Calibri' }),
                        ],
                        EMERALD_L,
                        { before: 40, after: 40 },
                    )
                );
            } else {
                children.push(
                    para(
                        [
                            new TextRun({ text: `${label}  `, bold: true, size: 20, color: GRAY_M, font: 'Calibri' }),
                            new TextRun({ text: opt, size: 20, color: GRAY_M, font: 'Calibri' }),
                        ],
                        { spacing: { before: 40, after: 40 }, indent: { left: convertInchesToTwip(0.3) } }
                    )
                );
            }
        });

        // Correct answer label
        children.push(
            para(
                [
                    new TextRun({ text: 'Correct Answer:  ', bold: true, size: 20, color: EMERALD, font: 'Calibri' }),
                    new TextRun({ text: mcq.correct_answer, bold: true, size: 20, color: EMERALD, font: 'Calibri', underline: { type: UnderlineType.SINGLE } }),
                ],
                { spacing: { before: 80, after: 60 }, indent: { left: convertInchesToTwip(0.1) } }
            )
        );

        // Explanation box
        if (mcq.explaination) {
            children.push(
                shadedPara(
                    [
                        new TextRun({ text: 'Explanation:  ', bold: true, size: 19, color: BLUE_T, font: 'Calibri' }),
                        new TextRun({ text: mcq.explaination, size: 19, color: BLUE_T, font: 'Calibri' }),
                    ],
                    BLUE_L,
                    { before: 60, after: 80 },
                )
            );
        }

        // Separator (except last)
        if (idx < mcqs.length - 1) {
            children.push(hrPara());
        }
    });

    const doc = new Document({
        sections: [{
            properties: {},
            headers: {
                default: new Header({
                    children: [
                        para([
                            new TextRun({ text: 'EduMate AI Assessment  —  Answer Key  (CONFIDENTIAL)', size: 16, color: '94A3B8', font: 'Calibri' }),
                        ], { alignment: AlignmentType.RIGHT }),
                    ],
                }),
            },
            footers: {
                default: new Footer({
                    children: [
                        para([
                            new TextRun({ text: 'Page ', size: 16, color: '94A3B8', font: 'Calibri' }),
                            new TextRun({ children: [PageNumber.CURRENT], size: 16, color: '94A3B8', font: 'Calibri' }),
                            new TextRun({ text: ' of ', size: 16, color: '94A3B8', font: 'Calibri' }),
                            new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 16, color: '94A3B8', font: 'Calibri' }),
                        ], { alignment: AlignmentType.CENTER }),
                    ],
                }),
            },
            children,
        }],
    });

    const blob = await Packer.toBlob(doc);
    saveAs(blob, 'EduMate_Answer_Key.docx');
}

// ─── Component ────────────────────────────────────────────────────────────────
const AssessmentView = ({ assessmentData }) => {
    const [viewMode, setViewMode] = useState('question');
    const [expandedExplanations, setExpandedExplanations] = useState({});
    const [downloading, setDownloading] = useState(false);

    if (!assessmentData || !assessmentData.mcqs) {
        return <div className="text-center p-8 text-gray-500">No assessment data available.</div>;
    }

    const { mcqs } = assessmentData;

    const toggleExplanation = (index) => {
        setExpandedExplanations(prev => ({ ...prev, [index]: !prev[index] }));
    };

    const handleDownload = async (fn) => {
        setDownloading(true);
        try { await fn(mcqs); } finally { setDownloading(false); }
    };

    return (
        <div className="w-full max-w-4xl mx-auto p-4 pb-20">

            {/* ── Sticky header ── */}
            <div className="sticky top-4 z-20 bg-white/80 dark:bg-gray-900/80 backdrop-blur-md rounded-2xl shadow-sm border border-gray-200 dark:border-gray-700 p-2 mb-8 flex justify-between items-center gap-2 flex-wrap">
                <h2 className="text-xl font-bold ml-4 text-gray-800 dark:text-gray-100 hidden sm:block">
                    Assessment Result
                </h2>

                {/* View toggle */}
                <div className="flex bg-gray-100 dark:bg-gray-800 p-1 rounded-xl">
                    <button
                        onClick={() => setViewMode('question')}
                        className={clsx(
                            'flex items-center space-x-2 px-4 py-2 rounded-lg text-sm font-medium transition-all duration-200',
                            viewMode === 'question'
                                ? 'bg-white dark:bg-gray-700 text-indigo-600 dark:text-indigo-400 shadow-sm'
                                : 'text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200'
                        )}
                    >
                        <FileText size={16} />
                        <span>Question Paper</span>
                    </button>
                    <button
                        onClick={() => setViewMode('answer')}
                        className={clsx(
                            'flex items-center space-x-2 px-4 py-2 rounded-lg text-sm font-medium transition-all duration-200',
                            viewMode === 'answer'
                                ? 'bg-white dark:bg-gray-700 text-emerald-600 dark:text-emerald-400 shadow-sm'
                                : 'text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200'
                        )}
                    >
                        <Key size={16} />
                        <span>Answer Key</span>
                    </button>
                </div>

                {/* Download button — context-aware */}
                {viewMode === 'question' ? (
                    <button
                        onClick={() => handleDownload(downloadQuestionDocx)}
                        disabled={downloading}
                        className="flex items-center gap-2 px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 active:scale-95 text-white text-sm font-semibold shadow-md shadow-indigo-500/30 transition-all duration-200 disabled:opacity-60 disabled:cursor-not-allowed"
                    >
                        <Download size={15} />
                        {downloading ? 'Generating…' : 'Download Questions (.docx)'}
                    </button>
                ) : (
                    <button
                        onClick={() => handleDownload(downloadAnswerKeyDocx)}
                        disabled={downloading}
                        className="flex items-center gap-2 px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 active:scale-95 text-white text-sm font-semibold shadow-md shadow-emerald-500/30 transition-all duration-200 disabled:opacity-60 disabled:cursor-not-allowed"
                    >
                        <Download size={15} />
                        {downloading ? 'Generating…' : 'Download Answer Key (.docx)'}
                    </button>
                )}
            </div>

            {/* ── Questions list ── */}
            <motion.div layout className="space-y-6">
                {mcqs.map((mcq, index) => (
                    <motion.div
                        key={index}
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: index * 0.05 }}
                        className="card hover:shadow-xl transition-shadow duration-300 border-l-4 border-l-transparent hover:border-l-indigo-500"
                    >
                        {/* Question header */}
                        <div className="flex items-start justify-between mb-4">
                            <div className="flex items-center gap-2 flex-wrap">
                                <span className="text-sm font-bold text-gray-400 uppercase tracking-wider">
                                    Question {mcq.question_no || index + 1}
                                </span>
                                {/* Bloom's badge — website only, never in Word docs */}
                                {mcq.bloom_level && (() => {
                                    const key = mcq.bloom_level.toLowerCase();
                                    const badge = BLOOMS_BADGE_STYLES[key];
                                    return badge ? (
                                        <span className={clsx(
                                            'inline-flex items-center gap-1 text-xs font-semibold px-2.5 py-0.5 rounded-full border',
                                            badge.classes
                                        )}>
                                            <Brain className="w-3 h-3" />
                                            {badge.label}
                                        </span>
                                    ) : (
                                        <span className="inline-flex items-center gap-1 text-xs font-semibold px-2.5 py-0.5 rounded-full border bg-gray-100 text-gray-600 dark:bg-gray-700 dark:text-gray-300 border-gray-200 dark:border-gray-600">
                                            <Brain className="w-3 h-3" />
                                            {mcq.bloom_level}
                                        </span>
                                    );
                                })()}
                            </div>
                            {viewMode === 'answer' && (
                                <span className="text-xs px-2 py-1 bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400 rounded-md font-mono">
                                    Correct: {mcq.correct_answer}
                                </span>
                            )}
                        </div>

                        <h3 className="text-lg font-medium text-gray-800 dark:text-gray-100 mb-6 leading-relaxed">
                            {mcq.question}
                        </h3>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                            {mcq.answer_options.map((option, optIndex) => {
                                const isAnswerMode = viewMode === 'answer';
                                const isCorrect = isAnswerMode && (
                                    option === mcq.correct_answer ||
                                    option.startsWith(`${mcq.correct_answer})`) ||
                                    option.startsWith(`${mcq.correct_answer}.`)
                                );
                                return (
                                    <div
                                        key={optIndex}
                                        className={clsx(
                                            'p-3 rounded-lg border text-sm transition-all duration-200 flex items-center',
                                            isCorrect
                                                ? 'bg-emerald-50 border-emerald-200 text-emerald-800 dark:bg-emerald-900/20 dark:border-emerald-800 dark:text-emerald-200 font-medium'
                                                : 'bg-gray-50 border-gray-100 text-gray-600 dark:bg-gray-700/50 dark:border-gray-700 dark:text-gray-300'
                                        )}
                                    >
                                        <div className={clsx(
                                            'w-6 h-6 rounded-full flex items-center justify-center mr-3 text-xs border flex-shrink-0',
                                            isCorrect
                                                ? 'bg-emerald-500 border-emerald-500 text-white'
                                                : 'bg-white dark:bg-gray-800 border-gray-300 dark:border-gray-600 text-gray-500'
                                        )}>
                                            {String.fromCharCode(65 + optIndex)}
                                        </div>
                                        {option}
                                        {isCorrect && <Check className="ml-auto w-4 h-4 text-emerald-600 flex-shrink-0" />}
                                    </div>
                                );
                            })}
                        </div>

                        {/* Explanation — answer mode only, website only */}
                        {viewMode === 'answer' && mcq.explaination && (
                            <div className="mt-6 pt-4 border-t border-gray-100 dark:border-gray-700">
                                <button
                                    onClick={() => toggleExplanation(index)}
                                    className="flex items-center text-sm text-indigo-600 dark:text-indigo-400 font-medium hover:underline focus:outline-none"
                                >
                                    {expandedExplanations[index]
                                        ? <><ChevronUp className="w-4 h-4 mr-1" /> Hide Explanation</>
                                        : <><ChevronDown className="w-4 h-4 mr-1" /> Show Explanation</>
                                    }
                                </button>
                                <motion.div
                                    initial={false}
                                    animate={{ height: expandedExplanations[index] ? 'auto' : 0, opacity: expandedExplanations[index] ? 1 : 0 }}
                                    transition={{ duration: 0.3 }}
                                    className="overflow-hidden"
                                >
                                    <div className="pt-2 text-sm text-gray-600 dark:text-gray-400 leading-relaxed bg-indigo-50/50 dark:bg-indigo-900/10 p-3 rounded-lg mt-2">
                                        <span className="font-semibold text-indigo-700 dark:text-indigo-300">Explanation: </span>
                                        {mcq.explaination}
                                    </div>
                                </motion.div>
                            </div>
                        )}
                    </motion.div>
                ))}
            </motion.div>
        </div>
    );
};

export default AssessmentView;
